### ISSUE TITLE
Part of 0.7.0 revamp: Refer to website for instructions?

### ISSUE THREAD

**Issue by Ben-PH** [seed-rs/seed-quickstart#20]
The website provides more context and referring to that could could prevent duplication issues.  

The Readme in this repo could serve for more conceptual content, with things like instructions, guides, etc., managed from the site and linked to.

**Comment by MartinKavik** [comment]
The source of truth should be always the quickstart's repo. There are already 3 quickstarts and there will be more - it would impractical to have all info on the website - once we decide to use e.g. Seeder in all website guides instead of this one, users wouldn't be able to use this quickstart. Also there would be synchronization problems sooner or later.

This quickstart is the oldest and the least maintained one, so many things are missing here.
I'll try to improve it and then you can focus on it and improve it :)

**Comment by Ben-PH** [comment]
nice. Tag me if there's anything I can help with. Closing - question addressed.
